<?php
/**
*   SimpleCaptcha
*   Simple image-based macthematical captcha
*
*   @version 2.6.0
*   https://github.com/foo123/simple-captcha
*
**/

if (!class_exists('SimpleCaptcha', false))
{
class SimpleCaptcha
{
    const VERSION = '2.6.0';

    private $opts = null;
    private $captcha = null;
    private $hmac = null;

    public function __construct()
    {
        $this->captcha = null;
        $this->hmac = null;
        $this->opts = array();
        $this->option('secret_key', 'SECRET_KEY');
        $this->option('secret_salt', 'SECRET_SALT_');
        $this->option('difficulty', 1); // 0 (very easy) to 3 (more difficult)
        $this->option('distortion_type', 1); // distortion type: 1: position distortion, 2: scale distortion
        $this->option('distortion', null); // distortion amplitudes by difficulty
        $this->option('num_terms', 2); // default
        $this->option('max_num_terms', -1); // default, same as num_terms
        $this->option('min_term', 1); // default
        $this->option('max_term', 20); // default
        $this->option('has_multiplication', true); // default
        $this->option('has_division', true); // default
        $this->option('has_equal_sign', true); // default
        $this->option('color', 0x121212); // text color
        $this->option('background', 0xffffff); // background color
    }

    public function option($key, $val = null)
    {
        $nargs = func_num_args();
        if (1 == $nargs)
        {
            return isset($this->opts[$key]) ? $this->opts[$key] : null;
        }
        elseif (1 < $nargs)
        {
            $this->opts[$key] = $val;
        }
        return $this;
    }

    public function getCaptcha()
    {
        if (empty($this->captcha)) $this->generate();
        return $this->captcha;
    }

    public function getHash()
    {
        if (empty($this->captcha)) $this->generate();
        return $this->hmac;
    }

    public function reset()
    {
        $this->captcha = null;
        $this->hmac = null;
        return $this;
    }

    public function validate($answer = null, $hmac = null)
    {
        if (is_null($answer) || empty($hmac)) return false;
        $algo = function_exists('hash') ? 'sha256' : 'sha1';
        $hash = hash_hmac($algo, (string)$this->option('secret_salt') . (string)$answer, (string)$this->option('secret_key'));
        return hash_equals($hash, (string)$hmac);
    }

    private function generate()
    {
        $difficulty = min(3, max(0, (int)$this->option('difficulty')));
        $distortion_type = min(2, max(0, (int)$this->option('distortion_type')));
        $distortion = $this->option('distortion');
        $num_terms = max(1, (int)$this->option('num_terms'));
        $max_num_terms = (int)$this->option('max_num_terms');
        $min_term = max(0, (int)$this->option('min_term'));
        $max_term = max(0, (int)$this->option('max_term'));
        $has_mult = (bool)$this->option('has_multiplication');
        $has_div = (bool)$this->option('has_division');
        $has_equal = (bool)$this->option('has_equal_sign');
        $color = $this->option('color');
        $background = $this->option('background');

        if (!is_array($color) && !is_callable($color)) $color = array($color);
        if (!is_array($background) && !is_callable($background)) $background = array($background);
        if (is_array($color)) $color = array_map(array($this, 'int'), $color);
        if (is_array($background)) $background = array_map(array($this, 'int'), $background);

        if ($max_num_terms > $num_terms)
        {
            $num_terms = mt_rand($num_terms, $max_num_terms);
        }

        // generate mathematical formula
        list($formula, $result) = $this->formula($num_terms, $min_term, $max_term, $has_mult, $has_div, $has_equal, $difficulty);

        // compute hmac of result
        $algo = function_exists('hash') ? 'sha256' : 'sha1';
        $this->hmac = hash_hmac($algo, (string)($this->option('secret_salt') ? $this->option('secret_salt') : '') . (string)$result, $this->option('secret_key'));

        // create image captcha with formula depending on difficulty
        $captcha = $this->image($formula, $color, $background, $difficulty, $distortion_type, $distortion);

        // output image
        ob_start(); imagepng($captcha);
        $this->captcha = 'data:image/png;base64,' . base64_encode(ob_get_clean());

        // free memory
        imagedestroy($captcha);

        return $this;
    }

    private function formula($terms, $min, $max, $has_mult, $has_div, $has_equal, $difficulty)
    {
        // generate mathematical formula
        $formula = array();
        $result = 0;
        $factor = 0;
        $divider = 0;
        for ($i=0; $i<$terms; ++$i)
        {
            $x = (int)mt_rand($min, $max);
            if (($result > $x) && mt_rand(0, 1))
            {
                // randomly use plus or minus operator
                $x = -$x;
            }
            elseif ($has_mult && ($x <= 10) && mt_rand(0, 1))
            {
                // randomly use multiplication factor
                $factor = (int)mt_rand(2, 3);
            }
            elseif ($has_div && (0 == $x % 2) && mt_rand(0, 1))
            {
                // randomly use division factor
                $divider = (int)(0 == $x % 3 ? mt_rand(2, 3) : 2);
            }
            if (0 < $factor)
            {
                $result += $x * $factor;
                if (0 > $x)
                {
                    $formula[] = '-';
                    $formula = array_merge($formula, str_split((string)abs($x)));
                    $formula[] = '×';
                    $formula = array_merge($formula, str_split((string)$factor));
                }
                else
                {
                    if (0 < $i) $formula[] = '+';
                    $formula = array_merge($formula, str_split((string)$x));
                    $formula[] = '×';
                    $formula = array_merge($formula, str_split((string)$factor));
                }
            }
            elseif (0 < $divider)
            {
                $result += floor($x / $divider);
                if (0 > $x)
                {
                    $formula[] = '-';
                    $formula = array_merge($formula, str_split((string)abs($x)));
                    $formula[] = '÷';
                    $formula = array_merge($formula, str_split((string)$divider));
                }
                else
                {
                    if (0 < $i) $formula[] = '+';
                    $formula = array_merge($formula, str_split((string)$x));
                    $formula[] = '÷';
                    $formula = array_merge($formula, str_split((string)$divider));
                }
            }
            else
            {
                $result += $x;
                if (0 > $x)
                {
                    $formula[] = '-';
                    $formula = array_merge($formula, str_split((string)abs($x)));
                }
                else
                {
                    if (0 < $i) $formula[] = '+';
                    $formula = array_merge($formula, str_split((string)$x));
                }
            }
            $factor = 0;
            $divider = 0;
        }
        if ($has_equal)
        {
            $formula[] = '=';
            $formula[] = '?';
        }
        return array($formula, $result);
    }

    private function image($chars, $color, $background, $difficulty, $distortion_type, $distortion)
    {
        $bitmaps = $this->chars();

        $cw = $bitmaps['width'];
        $ch = $bitmaps['height'];
        $n = count($chars);
        $space = 1;
        $x0 = 10;
        $y0 = 10;
        $w = $n * $cw + ($n-1) * $space + 2 * $x0;
        $h = $ch + 2 * $y0;
        $wh = $w*$h;

        // img bitmap
        $imgb = array_fill(0, $wh, 0);
        $img = imagecreatetruecolor($w, $h);
        $x1 = 0;
        $y1 = $h/2;
        $x2 = $w;
        $y2 = $h/2;
        for ($i=0,$x=0,$y=0; $i<$wh; ++$i,++$x)
        {
            if ($x >= $w) {$x = 0; ++$y;}
            $imgb[$i] = 0;
            $c = $this->colorAt($x, $y, $background, $x1, $y1, $x2, $y2);
            imagesetpixel($img, $x, $y, imagecolorallocate($img, $c[0], $c[1], $c[2]));        }

        // render chars
        foreach ($chars as $char)
        {
            $charbmp =& $bitmaps['chars'][$char]['bitmap'];
            $x1 = 0;
            $y1 = rand(0, $ch-1);
            $x2 = $cw-1;
            $y2 = rand(0, $ch-1);
            for ($x=0; $x<$cw; ++$x)
            {
                for ($y=0; $y<$ch; ++$y)
                {
                    $alpha = $charbmp[$x + $cw*$y];
                    if (0 < $alpha)
                    {
                        $imgb[$x0+$x + $w*($y0+$y)] = $alpha;
                    }
                }
            }
            $x0 += $cw + $space;
        }

        if ((0 < $difficulty) && (0 < $distortion_type))
        {
            switch($distortion_type)
            {
                case 2:
                    // create scale-distorted GD image based on difficulty level
                    $phase = (float)mt_rand(0, 2) * 3.14 / 2.0;
                    $amplitude = is_array($distortion) && isset($distortion[(string)$difficulty]) ? (float)$distortion[(string)$difficulty] : (3 == $difficulty ? 0.5 : (2 == $difficulty ? 0.25 : 0.15));
                    $x0 = max(0, round(($w - $n*(1.0+$amplitude)*$cw - ($n-1)*$space) / 2));
                    for ($k=0; $k<$n; ++$k)
                    {
                        $scale = (1.0 + $amplitude * sin($phase + 6.28 * 2 * $k / $n));
                        $sw = min($w, round($scale * $cw));
                        $sh = min($h, round($scale * $ch));
                        $y0 = max(0, round(($h - $sh) / 2));
                        $x1 = 0;
                        $y1 = $sh/2;
                        $x2 = $sw;
                        $y2 = $sh/2;
                        for ($ys=0; $ys<$sh; ++$ys)
                        {
                            $y = max(0, min($h-1, round(10 + $ys / $scale)));
                            for ($xs=0; $xs<$sw; ++$xs)
                            {
                                $x = max(0, min($w-1, round(10 + $k*($cw+$space) + $xs / $scale)));
                                $alpha = $imgb[$x + $y*$w];
                                if (0 < $alpha)
                                {
                                    $alpha /= 255.0;
                                    $c = $this->colorAt($xs, $ys, $color, $x1, $y1, $x2, $y2);
                                    $rgb = imagecolorat($img, $x0+$xs, $y0+$ys);
                                    imagesetpixel($img, $x0+$xs, $y0+$ys, imagecolorallocate($img, $this->clamp((($rgb >> 16) & 255)*(1-$alpha) + $alpha*$c[0]), $this->clamp((($rgb >> 8) & 255)*(1-$alpha) + $alpha*$c[1]), $this->clamp((($rgb) & 255)*(1-$alpha) + $alpha*$c[2])));
                                }
                            }
                        }
                        $x0 += $space + $sw;
                    }
                    break;
                case 1:
                default:
                    // create position-distorted GD image based on difficulty level
                    $phase = (float)mt_rand(0, 2) * 3.14 / 2.0;
                    $amplitude = is_array($distortion) && isset($distortion[(string)$difficulty]) ? (float)$distortion[(string)$difficulty] : (3 == $difficulty ? 5.0 : (2 == $difficulty ? 3.0 : 1.5));
                    $x1 = 0;
                    $y1 = $ch/2;
                    $x2 = $cw;
                    $y2 = $ch/2;
                    for ($y=0; $y<$h; ++$y)
                    {
                        $y0 = $y;
                        for ($x=0; $x<$w; ++$x)
                        {
                            $x0 = $x;
                            $y0 = max(0, min($h-1, round($y + $amplitude * sin($phase + 6.28 * 2 * $x / $w))));
                            $alpha = $imgb[$x0 + $y0*$w];
                            if (0 < $alpha)
                            {
                                $alpha /= 255.0;
                                $xc = $x - 10 + $space - floor(($x - 10 + $space)/($cw + $space))*($cw + $space);
                                $yc = $y - 10;
                                $c = $this->colorAt($xc, $yc, $color, $x1, $y1, $x2, $y2);
                                $rgb = imagecolorat($img, $x, $y);
                                imagesetpixel($img, $x, $y, imagecolorallocate($img, $this->clamp((($rgb >> 16) & 255)*(1-$alpha) + $alpha*$c[0]), $this->clamp((($rgb >> 8) & 255)*(1-$alpha) + $alpha*$c[1]), $this->clamp((($rgb) & 255)*(1-$alpha) + $alpha*$c[2])));
                            }
                        }
                    }
            }
        }
        else
        {
            // create non-distorted GD image
            $x1 = 0;
            $y1 = $ch/2;
            $x2 = $cw;
            $y2 = $ch/2;
            for ($y=0,$yw=0; $y<$h; ++$y,$yw+=$w)
            {
                for ($x=0; $x<$w; ++$x)
                {
                    $alpha = $imgb[$x + $yw];
                    if (0 < $alpha)
                    {
                        $alpha /= 255.0;
                        // x = x0 + i*cw + (i-1)*space + xc
                        // xc = x - x0 + space - i*(cw + space)
                        $xc = $x - 10 + $space - floor(($x - 10 + $space)/($cw + $space))*($cw + $space);
                        $yc = $y - 10;
                        $c = $this->colorAt($xc, $yc, $color, $x1, $y1, $x2, $y2);
                        $rgb = imagecolorat($img, $x, $y);
                        imagesetpixel($img, $x, $y, imagecolorallocate($img, $this->clamp((($rgb >> 16) & 255)*(1-$alpha) + $alpha*$c[0]), $this->clamp((($rgb >> 8) & 255)*(1-$alpha) + $alpha*$c[1]), $this->clamp((($rgb) & 255)*(1-$alpha) + $alpha*$c[2])));
                    }
                }
            }
        }

        // free memory
        $bitmaps = null;
        $imgb = null;

        return $img;
    }

    private function colorAt($x, $y, $colors, $x1, $y1, $x2, $y2)
    {
        //if (!empty($colors['image']) && !empty($colors['width']) && !empty($colors['height'])) return $this->patternAt($x, $y, $colors);
        if (is_callable($colors)) return call_user_func($colors, $x, $y);
        // linear gradient interpolation between colors
        $dx = $x2 - $x1;
        $dy = $y2 - $y1;
        $vert = 0 == $dx;
        $hor = 0 == $dy;
        $f = 2*$dx*$dy;
        $l = count($colors) - 1;
        $px = $x - $x1;
        $py = $y - $y1;
        $t = $hor && $vert ? 0 : ($vert ? $py/$dy : ($hor ? $px/$dx : ($px*$dy + $py*$dx)/$f));
        if (0 >= $t)
        {
            $c0 = $c1 = 0;
            $t = 0;
        }
        elseif (1 <= $t)
        {
            $c0 = $c1 = $l;
            $t = 1;
        }
        else
        {
            $c0 = floor($l*$t);
            $c1 = $l == $c0 ? $c0 : ($c0 + 1);
        }
        $rgb0 = $colors[$c0];
        $rgb1 = $colors[$c1];
        $t = $c1 > $c0 ? ($l*$t - $c0)/($c1 - $c0) : $t;
        return array(
        $this->clamp((1-$t)*(($rgb0 >> 16) & 255) + $t*(($rgb1 >> 16) & 255)),
        $this->clamp((1-$t)*(($rgb0 >> 8) & 255) + $t*(($rgb1 >> 8) & 255)),
        $this->clamp((1-$t)*(($rgb0) & 255) + $t*(($rgb1) & 255))
        );
    }

    /*private function patternAt($x, $y, $pattern)
    {
        $x = round($x) % $pattern['width'];
        $y = round($y) % $pattern['height'];
        if (0 > $x) $x += $pattern['width'];
        if (0 > $y) $y += $pattern['height'];
        $i = ($x + $y*$pattern['width']) << 2;
        return array(
        $pattern['image'][$i + 0],
        $pattern['image'][$i + 1],
        $pattern['image'][$i + 2]
        );
    }*/

    public function int($x)
    {
        return (int)$x;
    }

    private function clamp($value)
    {
        return max(0, min(255, round($value)));
    }

    private function chars()
    {
        return array (
          'fontSize' => 20,
          'width' => 12,
          'height' => 15,
          'chars' =>
          array (
            0 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                94,
                255,
                255,
                0,
                0,
                0,
                222,
                255,
                139,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                94,
                255,
                255,
                0,
                0,
                0,
                222,
                255,
                139,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
              ),
            ),
            1 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                255,
                222,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                48,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
              ),
            ),
            2 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                222,
                255,
                139,
                0,
                0,
                0,
                222,
                255,
                139,
                0,
                0,
                0,
                255,
                182,
                0,
                0,
                0,
                0,
                48,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                94,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
              ),
            ),
            3 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                255,
                255,
                48,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                139,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
              ),
            ),
            4 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                182,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                182,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                48,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                139,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                222,
                222,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                139,
                255,
                48,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                48,
                255,
                139,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                139,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                48,
                0,
                139,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
              ),
            ),
            5 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                94,
                255,
                255,
                255,
                255,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                255,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                222,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                94,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
              ),
            ),
            6 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                94,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                139,
                0,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                94,
                255,
                222,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                94,
                255,
                255,
                222,
                0,
                0,
                0,
                139,
                255,
                182,
                0,
                0,
                94,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                48,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                255,
                48,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                139,
                255,
                222,
                0,
                0,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
              ),
            ),
            7 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                48,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
              ),
            ),
            8 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                0,
                94,
                255,
                255,
                255,
                255,
                255,
                94,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                139,
                255,
                139,
                0,
                0,
                0,
                94,
                255,
                182,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                182,
                255,
                139,
                0,
                0,
                0,
                94,
                255,
                222,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                48,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                222,
                0,
                0,
                0,
                0,
              ),
            ),
            9 =>
            array (
              'width' => 12,
              'height' => 15,
              'bitmap' =>
              array (
                0,
                0,
                0,
                182,
                255,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                139,
                255,
                94,
                0,
                0,
                0,
                222,
                255,
                0,
                0,
                0,
                0,
                0,
                222,
                222,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                255,
                255,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                182,
                255,
                182,
                0,
                0,
                0,
                182,
                255,
                255,
                48,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                222,
                255,
                48,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                0,
                182,
                255,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                222,
                0,
                0,
                0,
                182,
                255,
                48,
                0,
                0,
                0,
                48,
                255,
                182,
                0,
                0,
                0,
                139,
                255,
                222,
                0,
                0,
                0,
                222,
                255,
                48,
                0,
                0,
                0,
                0,
                255,
                255,
                255,
                255,
                255,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                94,
                0,
                0,
                0,
                0,
              ),
            ),
            '+' =>
            array (
              'width' => 12,
              'height' => 10,
              'bitmap' =>
              array (
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
              ),
            ),
            '-' =>
            array (
              'width' => 7,
              'height' => 2,
              'bitmap' =>
              array (
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                222,
                255,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
              ),
            ),
            '×' =>
            array (
              'width' => 12,
              'height' => 9,
              'bitmap' =>
              array (
                0,
                0,
                222,
                48,
                0,
                0,
                0,
                0,
                182,
                94,
                0,
                0,
                0,
                0,
                255,
                255,
                48,
                0,
                0,
                139,
                255,
                139,
                0,
                0,
                0,
                0,
                0,
                255,
                255,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                94,
                255,
                222,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                48,
                255,
                255,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                255,
                255,
                0,
                139,
                255,
                182,
                0,
                0,
                0,
                0,
                0,
                255,
                255,
                48,
                0,
                0,
                139,
                255,
                139,
                0,
                0,
                0,
                0,
                222,
                48,
                0,
                0,
                0,
                0,
                182,
                94,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
              ),
            ),
            '÷'=> array(
                'width'=> 11,
                'height'=> 8,
                'bitmap'=> array(
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    0,
                    0,
                    182,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                )
            ),
            '='=> array(
                'width'=> 12,
                'height'=> 6,
                'bitmap'=> array(
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    222,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    139,
                    0,
                    0,
                    222,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    139,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    222,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    139,
                    0,
                    0,
                    222,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    139,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                )
            ),
            '?'=> array(
                'width'=> 12,
                'height'=> 15,
                'bitmap'=> array(
                    0,
                    0,
                    0,
                    222,
                    255,
                    255,
                    255,
                    255,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    255,
                    94,
                    0,
                    0,
                    0,
                    182,
                    255,
                    182,
                    0,
                    0,
                    0,
                    139,
                    255,
                    255,
                    0,
                    0,
                    0,
                    255,
                    222,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    48,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    139,
                    255,
                    182,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    222,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    182,
                    255,
                    222,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    48,
                    255,
                    222,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    139,
                    255,
                    94,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    139,
                    255,
                    94,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    139,
                    255,
                    94,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    139,
                    255,
                    94,
                    0,
                    0,
                    0,
                    0,
                    0
                )
            )
          ),
        );
    }
}
}
